### ISSUE TITLE
Czy ten branch jest nam do czegos potrzebny?

### ISSUE THREAD

**Issue by JakJaj** [JakJaj/Stronghold-Guardians#16]
Dajcie mi znać czy kod z brancha feat/shop jest nam jeszcze do czegokolwiek potrzebny. Bo chciałem go usunąć ale nie wiem czy nie macie tam czegoś z czego będziecie jeszcze korzystali. 

Jeśli można to wywalić to dajcie znać w komentarzu i się go pozbędziemy a jeśli jest przydatny to się go będzie próbowało mergować.

**Comment by V3X3N** [comment]
Żaden kod nigdy, imo można wywalić

**Comment by JakJaj** [comment]
Ok, to usuwam.
