### ISSUE TITLE
Ostatnie rzeczy przed końcem

### ISSUE THREAD

**Issue by JakJaj** [JakJaj/Stronghold-Guardians#21]
@V3X3N powalcz z tymi branchami i jak będziesz mial wszystko gotowe żeby to zakończyć to daj znać w tym issue to zrobimy finalny merge.

@BartoszDeszcz pamiętaj żeby dopisać w tej prezentacji link do githuba i prześlij tą wersje na classroom.

**Comment by V3X3N** [comment]
Tak zrobię, powalczę

**Comment by BartoszDeszcz** [comment]
Link do prezentacji dodany, a prezentacja wysłana na classroom
